task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 12 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /kaggle/input/visdrone-2019-coco-format/train
    ann_file: /kaggle/input/visdrone-2019-coco-format/annotations_VisDrone_train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  total_batch_size: 16
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /kaggle/input/visdrone-2019-coco-format/val
    ann_file: /kaggle/input/visdrone-2019-coco-format/annotations_VisDrone_val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
